[build]
builder = "nixpacks"

[build.env]
PNPM_VERSION = "10.9.0"   # Corepack activates this

[deploy]
startCommand  = "pnpm --filter ./apps/frontend --workspace-root run start"
healthcheckPath = "/"
watchPaths = [
  "apps/frontend/**",
  "packages/ui/**"
]


# --- Frontend Service Definition ---
[[services]]
name = "frontend" # Optional, but helpful identifier
rootDir = "apps/frontend" 
healthcheckPath = "/"

[[services]]
name = "backend" # Optional, but helpful identifier
rootDir = "apps/backend"
