[build]
builder = "nixpacks"

[build.env]
PNPM_VERSION = "10.9.0"   # Corepack activates this

[deploy]
name = "frontend"
rootDir = "." 
startCommand  = "pnpm --filter ./apps/frontend --workspace-root run start"
healthcheckPath = "/"
watchPaths = [
  "apps/frontend/**",
  "packages/ui/**"
]
[services.build]
   cmds = ["pnpm build"]


